### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by jacobrosenthal** [Deserae/node-math#1]
When I run with no arguments it just says something cryptic about doing math. If I use -h or --help I dont get anything either.

```
Jacobs-MacBook-Air:node-math jacobrosenthal$ node index.js
[]
Why don't you try doing some math
Jacobs-MacBook-Air:node-math jacobrosenthal$ node index.js -h
[]
Why don't you try doing some math
Jacobs-MacBook-Air:node-math jacobrosenthal$ node index.js --help
[]
Why don't you try doing some math
Jacobs-MacBook-Air:node-math jacobrosenthal$ 
```

**Comment by Deserae** [comment]
Upcoming enhancements will fix this. :+1:

**Comment by Deserae** [comment]
Added a clearer message. I think it could be reworked even more in the future. The syntax in this seems very different than the one in cryptokitties.

**Comment by jacobrosenthal** [comment]
That would have appeared to have happened in commit 1f58d8fc72a38fcaf5d605063795ab00d0759541
