### ISSUE TITLE
Use of ./ for Yargs

### ISSUE THREAD

**Issue by Deserae** [Deserae/node-math#2]
When I use ./ I only get a permission denied message.

**Comment by jacobrosenthal** [comment]
These 2 searches should help

macos script "permission denied"
https://www.google.com/search?rlz=1C5CHFA_enUS722US724&q=macos+script+%22permission+denied%22&oq=macos+script+%22permission+denied%22&gs_l=psy-ab.3..0i22i30k1.7099.7540.0.7711.2.2.0.0.0.0.100.190.1j1.2.0....0...1.1.64.psy-ab..0.2.188...0i8i13i30k1._srJT1WyZAw

macos node script executable
https://www.google.com/search?rlz=1C5CHFA_enUS722US724&q=macos+node+script+executable&oq=macos+node+script+executable&gs_l=psy-ab.3...5405.5864.0.6006.6.5.0.0.0.0.115.477.4j1.5.0....0...1.1.64.psy-ab..2.0.0.orLpf9oYo9U

**Comment by Deserae** [comment]
./ - can open a file but only if it’s an executable. Otherwise, use node [filename] to execute.
